name: AskUI Run without Studio
on:
  # push:
  #   branches:
  #     - main
   workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      ui-controller:
        image: askuigmbh/askui-ui-controller:v0.11.2-chrome-100.0.4896.60-amd64
        ports:
          - 6769:6769
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Set up Android emulator
        uses: actions/setup-android@v2
        with:
          emulator-version: '30.0.12'
          sdk-version: '30'
      - name: Start emulator
        run: |
          # Start the emulator
          emulator -avd emulator-30 -no-window -no-audio &
          # Wait for the emulator to finish booting
          android-wait-for-emulator
      - name: Take screenshot
        run: |
          # Take a screenshot of the emulator
          adb shell screencap -p /sdcard/screenshot.png
          adb pull /sdcard/screenshot.png .
      - name: Upload screenshot as artifact
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png